name: container
on:
  pull_request:
    branches: [ master ]

 
jobs:
  logstash-docker:
    runs-on: -latest
    steps:
     - uses: actions/checkout@v2
       with: 
            fetch-depth: 2
     - run: echo "FOO=$(git diff --name-only HEAD~ HEAD)" >> $GITHUB_ENV
     - run: echo ${{ env.FOO }}
